name: Go

on:
  pull_request:
    branches: [ develop ]

jobs:

  build:
    name: WASP Build And Unit Test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build Test
      run: go build -v .

    - name: Unit Test
      run: go test -v .
